server:
  servlet:
    context-path: /api/guest

spring:
  application:
    name: church-guest-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/guest
token:
  secret: ZXNzYSBlaCBhIHRva2VuIGxvY2Fs

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG