server:
  servlet:
    context-path: /api/guest

spring:
  application:
    name: church-guest-api
  data:
    mongodb:
      uri: ${DATA_SOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  secret: ${JWT_SECRET}

notification:
  whatsGw:
    base-url: ${BASE_URL}
    apikey: ${API_KEY}
    phone_number: ${PHONE_NUMBER}
    adm_phone_number: ${ADM_PHONE_NUMBER}

pix:
  key: ${PIX_KEY}
  nome: ${NOME}
  cidade: ${CIDADE}
