apiVersion: v1
kind: Pod
metadata:
  name: guest-db
  labels:
    app: guest-db
spec:
  containers:
    - name: mongo
      image: mongo:latest
      volumeMounts:
        - mountPath: /data/db
          name: guest-pv
      ports:
        - containerPort: 27017
  volumes:
    - name: guest-pv
      persistentVolumeClaim:
        claimName: guest-pvc