apiVersion: v1
kind: PersistentVolume
metadata:
  name: guest-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: guest-disk-1
  storageClassName: standard