apiVersion: v1
kind: Pod
metadata:
  name: guest-api
  labels:
    app: guest-api
spec:
  containers:
  - name: guest-api
    image: njaneto/guest-api:1
    ports:
    - containerPort: 8080
    env:
      - name: DATA_SOURCE_URL
        value: mongodb://34.121.140.116:27017/guest