apiVersion: v1
kind: Pod
metadata:
  name: guest-api
  labels:
    app: guest-api
spec:
  containers:
  - name: guest-api
    image: njaneto/guest-api:2
    ports:
    - containerPort: 8080
    env:
      - name: DATA_SOURCE_URL
        value: mongodb://localhost:27017/guest
      - name: JWT_SECRET
        value: any