server:
  servlet:
    context-path: /api/guest

spring:
  application:
    name: church-guest-api
  data:
    mongodb:
      uri: ${DATA_SOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true